# Build step #1: build the React front end
FROM node:21-alpine as build-step
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY sys-stats/package.json  ./
COPY sys-stats/src ./src
COPY sys-stats/public ./public

RUN yarn install
RUN yarn build

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY ./2_containers/nginx.default.conf /etc/nginx/conf.d/default.conf

